### ISSUE TITLE
API Returned HTTP Status: 429

### ISSUE THREAD

**Issue by theslyprofessor** [cenkalti/AI-Writer#1]
Hello,

I love your plugin! It worked perfectly for a few days, but suddenly stopped functioning. I tried updating the API key, but I keep encountering the same error. I’m not sure what I might be doing wrong. It’s honestly the best app I’ve used, and I’ve come to rely on it heavily, so any assistance would be greatly appreciated!
<img width="259" alt="image" src="https://github.com/user-attachments/assets/37711168-bae8-46b2-ba85-49d6ac854847">

**Comment by cenkalti** [comment]
I'm glad to hear the app is useful for you. That 429 error code comes from OpenAI servers. It means you're using the API a lot and hitting a rate limit. The rate limits reset after a while.

- https://platform.openai.com/docs/guides/error-codes/api-errors
- https://platform.openai.com/docs/guides/rate-limits

**Comment by theslyprofessor** [comment]
Thanks for your response! I didn’t think I was using it that much, but it hasn't reset after several days. Is there a way I can keep using it without interruptions, maybe by paying for additional access? It also seems like I’m getting charged, so I want to make sure I understand the options.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cenkalti** [comment]
You might be using the same key in another app. Try making a new API key for AI Writer and don't use it in other apps.

Create a new API key here: https://platform.openai.com/api-keys

You can see which keys are in use on the right side of this page: https://platform.openai.com/usage/activity

Other than this, there's not much I can do from the application side since this error is coming from OpenAI servers.

Let me know if you have any questions.

**Comment by theslyprofessor** [comment]
Thanks for this info. I forgot to update you, but I've been unable to use it ever since. I've reset the API keys several times but with no luck. It's sad, because I find it to be much more useful than Apple Intelligence.

**Comment by theslyprofessor** [comment]
After I wrote that, I tried again, and it worked. I used AI-writer for this message. Hopefully, I won't lose access again, especially since I'm paying OpenAI for API usage. It doesn't make sense. Thanks again.

**Comment by theslyprofessor** [comment]
Back to 429 status, after literally only 3 rewrites over the span of 15 minutes, very short messages too :( It makes absolutely no sense to me why OpenAI would do this when you would think their business model would welcome paid API calls, which I absolutely have no objection paying for given the convenience

**Comment by theslyprofessor** [comment]
I read on Reddit that you need to manually pre-pay for credits in your OpenAI account. Even though I set a $20 monthly allowance, I still had to pre-pay with credits. This is different from how it was before. It might be worth noting. Thanks again for making such an awesome tool! It works now!

**Comment by cenkalti** [comment]
I'm glad your issue is resolved. Thanks for sharing the solution here.
