### ISSUE TITLE
Icon disappearing from Menu Bar

### ISSUE THREAD

**Issue by theslyprofessor** [cenkalti/AI-Writer#2]
I've been really getting into using this plugin and have created several prompts for it. It might be helpful to add a dropdown list to select your preferred prompt. For now, I've been copying and pasting from my Google Doc full of prompts. However, I've noticed that the application disappears from the menu bar, which prevents me from updating the settings. It doesn't show up as a process for me to restart either. This happens sometimes, and my only choice is to restart the computer.

<img width="607" alt="image" src="https://github.com/user-attachments/assets/9c7d4ca7-63af-4721-bf56-419696c56e00">

**Comment by cenkalti** [comment]
That's a lot of icons on your menu bar! :) There's a limit to how many icons macOS can show there.

I would try to reduce them. You can move some to the control center. Another option is to use a third-party app to hide some icons. Check out this link for inspiration: https://www.macrumors.com/2024/06/06/alternatives-bartender-mac-menu-bar/.

If you need to close or restart an app when its icon isn't visible, you can find it in Activity Monitor:
<img width="1072" alt="Screenshot 2024-10-21 at 3 09 12 PM" src="https://github.com/user-attachments/assets/064686b2-3a73-40b1-aa65-5f9b9839cd76">

I currently only use one prompt, so supporting more than one isn't on my list. However, I'm open to contributions. Feel free to send a PR.

**Comment by cenkalti** [comment]
I've released a new version and removed OpenAI requirement. Now, the app can talk with any LLM. I am using [Ollama](https://ollama.com/) myself to run a local LLM on my laptop. Take a look.
https://github.com/cenkalti/AI-Writer/releases/tag/v1.1.0

**Comment by theslyprofessor** [comment]
Thank you! These are cool developments. Do you have guidance on how to get started with ChatGPT on the new version? The interface is different enough where I haven't been able to successfully utilize my OpenAI API key. Many thanks,

**Comment by cenkalti** [comment]
I would like to improve documentation soon but you can use following settings for OpenAI API:
<img width="254" alt="image" src="https://github.com/user-attachments/assets/824c00f5-f78a-4179-8226-a4f355296969">

**Comment by theslyprofessor** [comment]
Thanks!

Nakul Tiruviluamala | Assistant Professor
Recording Arts and Technology, Program Lead
Commercial Music, Program Lead
Southwestern College | Chula Vista Campus
Building 84, Office 84-110
***@***.******@***.***> | (858) 248-3218 (cell)


From: Cenk Altı ***@***.***>
Date: Monday, November 4, 2024 at 7:39 AM
To: cenkalti/AI-Writer ***@***.***>
Cc: theslyprofessor ***@***.***>, Author ***@***.***>
Subject: Re: [cenkalti/AI-Writer] Icon disappearing from Menu Bar (Issue #2)

I would like to improve documentation soon but you can use following settings for OpenAI API:
image.png (view on web)<https://github.com/user-attachments/assets/824c00f5-f78a-4179-8226-a4f355296969>
